import os


BINANCE_SYMBOL = 'BTC/USDT'
TIMEFRAME = '15m'

RSI_PERIOD = 14
BOLLINGER_PERIOD = 20
BOLLINGER_STD_DEV = 2

CANDLE_RELEVANT_VALUE = 'close'

API_KEY = os.environ['API_KEY']
API_SECRET = os.environ['API_SECRET']

BYBIT_SYMBOL = 'BTCUSD'
BYBIT_ORDER_TYPE = 'Market'
BYBIT_BUYING_METHOD_NAME = 'Buy'
BYBIT_SELLING_METHOD_NAME = 'Sell'
